# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netz < Formula
  desc "Discover internet-wide misconfigurations while drinking coffee"
  homepage "https://github.com/spectralops/netz"
  version "0.2.0"
  license "MIT"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/netz/releases/download/v0.2.0/netz_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "b6f12dc5b827e205b6a641d8317a3042ca2c7b175bb51354b57ef164145fb0a8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/SpectralOps/netz/releases/download/v0.2.0/netz_0.2.0_Darwin_arm64.tar.gz"
    sha256 "490f299d897697162f68595ab65bf4a9b2832274878f7c676815ec398751fd5b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/netz/releases/download/v0.2.0/netz_0.2.0_Linux_x86_64.tar.gz"
    sha256 "483c2b3533d67a8d57f85cc1d697f20d55e599122efceabc4bf95f995b240ae0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/SpectralOps/netz/releases/download/v0.2.0/netz_0.2.0_Linux_arm64.tar.gz"
    sha256 "88a66f55e94161e6cf8885c47d6ae4aa00ee18ce51f2363f5b6466280211665a"
  end

  def install
    bin.install "netz"
  end
end
