# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Senv < Formula
  desc "Friends don't let friends leak secrets in terminal windows"
  homepage "https://github.com/spectralops/senv"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/senv/releases/download/v0.2.0/senv_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "435811d699e79cd4133d728e2cefd1dd3424226246176a418c722e06f0e627c4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/senv/releases/download/v0.2.0/senv_0.2.0_Linux_x86_64.tar.gz"
    sha256 "02d9d816fc6d609b9802df8113981da2d59fd82461f1582fa79f5ecb68f8026f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/SpectralOps/senv/releases/download/v0.2.0/senv_0.2.0_Linux_arm64.tar.gz"
    sha256 "fc95660f073d597729ec4e773fc294488c10db22e0bd876313db1354ed74872b"
  end

  def install
    bin.install "senv"
  end
end
