# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teller < Formula
  desc "A secret manager for developers - never leave your terminal for secrets"
  homepage "https://github.com/spectralops/teller"
  version "0.5.0"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/teller/releases/download/v0.5.0/teller_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "f0461361460d6bc1c0edf3d53d8aaf5b019113f44a5b0d87981e8f341cdcd53a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/SpectralOps/teller/releases/download/v0.5.0/teller_0.5.0_Darwin_arm64.tar.gz"
    sha256 "9f334b33127dcdca3caa6259666e90631ad5d21ad1746d749ed86825b5360959"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/teller/releases/download/v0.5.0/teller_0.5.0_Linux_x86_64.tar.gz"
    sha256 "630f9078bc2adc5a78ab2ceca148706ca18daf0a535b61c4ecb9822f556f7173"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/SpectralOps/teller/releases/download/v0.5.0/teller_0.5.0_Linux_arm64.tar.gz"
    sha256 "5bd82a5247296bb887f4d6aceba3077402a5c5422ead24e7443e8f80c2a6d1de"
  end

  def install
    bin.install "teller"
    ln_s bin/"teller", bin/"tlr"
  end
end
