# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teller < Formula
  desc "A secret manager for developers - never leave your terminal for secrets"
  homepage "https://github.com/spectralops/teller"
  version "0.6.0"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/teller/releases/download/v0.6.0/teller_0.6.0_Darwin_x86_64.tar.gz"
    sha256 "992cb8fb2973f12be16932a495fb3a0f6b717750bfca5d8bbdbbdc1c9ae5c5c9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/SpectralOps/teller/releases/download/v0.6.0/teller_0.6.0_Darwin_arm64.tar.gz"
    sha256 "6494f9544ad1558949ec468b85e2618155f540f9c6074f68cae750bd19a0b4d3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/teller/releases/download/v0.6.0/teller_0.6.0_Linux_x86_64.tar.gz"
    sha256 "73a3799f628fddc39571ddf750727c88ae528c51303a0b50d06fe961fbdfe8cf"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/SpectralOps/teller/releases/download/v0.6.0/teller_0.6.0_Linux_arm64.tar.gz"
    sha256 "f7ccf119786b198b8b2846c417dcd05ee70138dd67a14bc3a665b55904d14b36"
  end

  def install
    bin.install "teller"
    ln_s bin/"teller", bin/"tlr"
  end
end
