# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teller < Formula
  desc "A secret manager for developers - never leave your terminal for secrets"
  homepage "https://github.com/spectralops/teller"
  version "1.0.0"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/teller/releases/download/v1.0.0/teller_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "a710d66a2151a03b0b785f0cfb68be2269d0f6d47e558da2efc3461b93644fe5"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/SpectralOps/teller/releases/download/v1.0.0/teller_1.0.0_Darwin_arm64.tar.gz"
    sha256 "b1bf62ac1a6d1b2fb21a1014f745d3d66ff2031093a0b44137a6da01620d5546"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SpectralOps/teller/releases/download/v1.0.0/teller_1.0.0_Linux_x86_64.tar.gz"
    sha256 "70db09acc8d359f71ebb703203b575320f1fb8f56b976f01eab9d13a208f64f6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/SpectralOps/teller/releases/download/v1.0.0/teller_1.0.0_Linux_arm64.tar.gz"
    sha256 "34b39ad0124319d5a35127cebf640222a4c3ba785d6693b7fde567f0956ba2a1"
  end

  def install
    bin.install "teller"
    ln_s bin/"teller", bin/"tlr"
  end
end
